// Leveraging tool-calling to interact with a retrieval step has another benefit, which is that the query for the retrieval is generated by our model.
// This is especially important in a conversational setting, where user queries may require contextualization based on the chat history.
